#!/bin/bash
#SBATCH --cpus-per-task=1		#application monothread
#SBATCH --mem-per-cpu=2G		

#boucle sur toutes les covariables
for k in {1..3}
do
#boucle sur tous les fichiers resultats
for i in {1..26}
do
file1=$(echo "/home/chemin/snpdet.sub""$i""")             # chemin complet, pas de lien ~
file2=$(echo "Poolseq.sub""$i""_summary_betai_reg.out")   # adapter le prefixe
sed -e "s/[[:space:]]\+/ /g" $file1 > SubSNP              # sed remplace tous les séparateurs par tabulation, ça évite les bugs
sed -e "s/[[:space:]]\+/ /g" $file2 | awk -vK="$k" '{if($1 == K) {print}}' - > SubBetai #ne copie que les resultats de la covariable k
paste SubSNP SubBetai >> Poolseq.Betai-Cov$k.merged				# merge les SNP avec les résultats dans un fichier pour la covariable k
done                                                      #les résultats de 1 à 25 sont concaténés à la suite
#tri par chromosome et par position
sort -k1,1 -k2,2n GWAS-13pops-chr1_C8.Betai-Cov$k.merged > GWAS-13pops-chr1_C8.Betai-Cov$k.merged.sorted		# <-- corriger le nom
#reconstruit l'entête
sed -i '1i chr pos All1 All2 COVARIABLE MRK M_Pearson SD_Pearson BF(dB) Beta_is SD_Beta_is eBPis' GWAS-13pops-chr1_C8.Betai-Cov$k.merged.sorted 		# <-- corriger le nom
#supprime les fichiers tmp
rm SubSNP
rm SubBetai
done                                                      #chaque covariable donne un fichier complet de résultats.
